### PR TITLE
Fix tests

### LINKED ISSUE #17: Fix and improve the tests of this package

### PR DESCRIPTION
**Pull request by fersilva16**
closes #17

### CODE REVIEW

**Review by sibelius — APPROVED** [review]

File: packages/errorField/ErrorField.ts [hunk 1]
```diff
@@ -86,4 +84,4 @@ function transform(file: FileInfo, api: API, options: Options) {
 }
 
 export const parser = 'tsx';
-export default errorField;
+export default transform;
```
Comment (noghartt) [inline packages/errorField/ErrorField.ts:87]: I made a mistake in this case, sorry :(

We should export `transform` as named export too, to import in other packages and compose some codemods.

**Review by noghartt — APPROVED** [review]

File: packages/errorField/ErrorField.ts (hunk 1 above)
Comment (fersilva16) [reply packages/errorField/ErrorField.ts:87]: Do you mean `export const errorField = transform`? I think it's not needed because we can just import the default with `import errorField from '@codemods/error-field';`
